name: Build Images

on: push

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build test
        uses: docker/build-push-action@v2
        with:
          context: .
          file: test/Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          tags: drsanwujiang/dicerobot:test

  build_images:
    needs: test

    name: Build Images

    runs-on: ubuntu-latest

    strategy:
      matrix:
        dicerobot: ["3.0.0", "3.0.1", "3.0.2", "latest"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set full names of the Docker image
        id: set_full_names
        run: echo "::set-output name=full_names::drsanwujiang/dicerobot:${{ matrix.dicerobot }}"

      - name: Build and push version ${{ matrix.dicerobot }}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: dockerfiles/${{ matrix.dicerobot }}/Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          push: true
          tags: ${{ steps.set_full_names.outputs.full_names }}

      - name: Image digest of version ${{ matrix.dicerobot }}
        run: echo ${{ steps.docker_build.outputs.digest }}
